# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# Import des routes définies avec les attributs dans src/Controller
controllers:
    resource: '../src/Controller/'
    type: attribute
